### ISSUE TITLE
FYI: pack, unpack, login, preview and publish api

### ISSUE THREAD

**Issue by lsongdev** [thedreamwork/unwxapkg#3]
Awesome works!

FYI:
+ login, preview, publish: https://github.com/song940/wechat-lite/blob/master/wxapp/index.js
+ unpack: https://github.com/song940/wechat-lite/blob/master/wxapp/unpack.js
+ pack: https://github.com/song940/wechat-lite/blob/master/wxapp/pack.js

**Comment by baniyasi** [comment]
？
